[ffmpeg]
  bin = "ffmpeg"

[ffmpeg.codecs]
  [ffmpeg.codecs."*"]
    args = [
        # 文件名
        "-i",
        "%i",
        # 分辨率
        "-s",
        "%s",
        # bit rate
        "-b",
        "%b",
        # video codec 这里先写死vp9
        "-vcodec",
        "libvpx-vp9",
        # audio codec 这里先写死opus
        "-acodec",
        "opus",
        # 默认命名为output.webm
        "output.webm"
    ]