[ffmpeg]
  bin = "ffmpeg"

[ffmpeg.codecs]
  [ffmpeg.codecs."*"]
    args = [
        # 文件名
        "-i",
        "%i",
        # 分辨率
        "-s",
        "%s",
        # bit rate
        "-b:v",
        "%b:v",
        "-b:a",
        "%b:a",
        # video codec 这里先写死vp9
        "-vcodec",
        "libvpx-vp9",
        # audio codec 这里先写死opus
        "-acodec",
        "opus",
        "-strict",
        "-2",
        # 默认命名为output.webm
        "output.webm"
    ]
  [ffmpeg.codecs."net"]
    args = [
      # 文件名
        "-i",
        "%i",
        # 分辨率
        "-s",
        "%s",
        # 格式
        "-f",
        "%f",
        # bit rate
        "-b:v",
        "%b:v",
        "-b:a",
        "%b:a",
        # video codec 这里先写死vp9
        "-vcodec",
        "libvpx-vp9",
        # audio codec 这里先写死opus
        "-acodec",
        "opus",
        "-strict",
        "experimental",
        # 如果preset和ultrafast同时注释是ok的
        # "-preset",        
        # 这一行注释的话，会报错：没有合适的输出格式
        # "ultrafast",
        # 没有这一行的话，会把后面的frag_keyframe等当成输出文件

      # 有关faststart 
      # 正常情况下，MP4复用器在文件末尾的音频流（“mdat”原子） 之后写入“moov”原子。
      # 这导致用户需要在播放之前完全下载文件。
      # faststart 将 moov前移，会更快

      # 有关 frag_keyframe
      # 输出的视频将会是分片的，fragment

      # 有关 empty_moov
      # empty_moov will cause output to be 100% fragmented; 
      # without this the first fragment will be muxed as a short movie (using moov) followed by the rest of the media in fragments,

        # 这一行不能注释，注释的话会报错，至少需要一个输出文件
        # 如果同时注释，是能够执行的。
      # "-movflags", 
      # "frag_keyframe+empty_moov+faststart", 

        # 默认使用管道输出
        "pipe:1"
    ]